name: 'helm-deploy-eks'
description: 'Run a helm command against an EKS cluster using an access and secret key'
inputs:
  command:
    description: "Your command (kubectl or helm)"
    required: true
  access_key:
    description: "AWS Access Key"
    required: true
  secret_key:
    description: "AWS Secret Key"
    required: true
  region:
    description: "The region the cluster is deployed in"
    required: true
  cluster_name:
    description: "The name of the EKS cluster"
    required: true
outputs:
  result:
    description: "Output returned by your Helm or kubectl command"
runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - ${{ inputs.command }}
    - ${{ inputs.access_key }}
    - ${{ inputs.secret_key }}
    - ${{ inputs.region }}